cargo-features = ["edition2021"]

[package]
name = "sci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arbitrary = "1.0.1"
derive_more = "0.99.16"
num = "0.4.0"
